Metricas:
  - EarningsPerShareDiluted
  - NetIncomeLoss
  - OperatingIncomeLoss
  - Revenues
  - GrossProfit
  - CostsAndExpenses
  - Assets
  - Liabilities
  - Equity
  - WheightedAverageNumberOfSharesOutstandingDiluted
  - StockholdersEquityNoteStockSplitConversionRatio1
  - NoncurrentAssets
Simbolos:
  - AAPL
  - ANET
  - CORT
  - CPRX
  - USLM
  - PGR
  - NVDA
  - TPL
  - V
  - UNH
  - SEZL
BaseDatos:
  Tipo: SQLServer
  Nombre: JHProgress
  Servidor: localhost\SQLEXPRESS
  String: DRIVER={ODBC Driver 17 for SQL Server};SERVER=localhost;DATABASE=JHProgress;Trusted_Connection=yes;
  TablaFundamentales: TMP_TB_Fundamentales
